// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package org.jboss.jmx.connector.notification;

public final class RMIClientNotificationListener_Stub
    extends java.rmi.server.RemoteStub
    implements org.jboss.jmx.connector.notification.RMIClientNotificationListenerInterface
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_handleNotification_0;
    
    static {
	try {
	    $method_handleNotification_0 = org.jboss.jmx.connector.notification.RMIClientNotificationListenerInterface.class.getMethod("handleNotification", new java.lang.Class[] {javax.management.Notification.class, java.lang.Object.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RMIClientNotificationListener_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of handleNotification(Notification, Object)
    public void handleNotification(javax.management.Notification $param_Notification_1, java.lang.Object $param_Object_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_handleNotification_0, new java.lang.Object[] {$param_Notification_1, $param_Object_2}, -1982336311472540462L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
